### ISSUE TITLE
2023-w04 -- how to make non-interactive version of the chart?

### ISSUE THREAD

**Issue by erdnaxel** [AlbertRapp/PublicTidyTuesday#1]
I really like the chart that you created for in 2023-w04 and I plan to use the ggigraph package in the future. 

I sometimes find myself in situations where I can't create interactive content. I'm wondering if you know of a package that would create the same kind of bars as geom_tile_interactive, but in a static version? 

I looked at geom_tile in ggplot, but it doesn't seem designed to create bars. 

I've searched any which way I could think of, but I'm not finding anything. There another example of this kind of chart [here](https://github.com/bbc/bbplot/blob/master/chart_examples/bbplot_example_plots.png), but they don't provide the code for this particular chart.

Thanks!

**Comment by AlbertRapp** [comment]
I'd indeed use geom_tile() to get the job done. In my code for this week's tidyTuesday you can just take the ggplot object and remove all the `_interactive()` parts in the geom. This would create a static analog of my interactive plot.

To use geom_tile() for bar plots you need to manually place them on top of each other. That's what I've done in my code as well. The code chunk that prepares the data as necessary was
```
survivalists |> 
  filter(season == 1)  |> 
  arrange(days_lasted) |> 
  select(name, days_lasted, result, reason_tapped_out) |> 
  mutate(active_days = map(days_lasted, ~(0:.))) |> 
  unnest(active_days)
```

And in the ggplot I've mapped `active_days` to the `x`-aesthetic (use the `y` aesthetic if you want to have it the other way around): `ggplot(aes(active_days, result, fill = name))`

**Comment by erdnaxel** [comment]
thanks for the response. i was able to create the chart, but the bars don't look the same as what you have. The feature I was hoping to recreate is to have the bars divided in units, so that if we want to know exactly how many days someone lasted, we can just count the squares.

![image](https://user-images.githubusercontent.com/63831549/214890598-dda8959b-dfd2-4029-9c2e-8708ba93d3ad.png)

vs

![image](https://user-images.githubusercontent.com/63831549/214890859-4624c241-8bd6-4a75-9615-091681985b35.png)

**Comment by AlbertRapp** [comment]
Don't forget to set the `color` of the tiles. I have used `color = 'white'` :)

**Comment by erdnaxel** [comment]
it worked! thank you so much, it really made my day!!!

![image](https://user-images.githubusercontent.com/63831549/214923487-f8fe3a3b-8383-4f4c-b0ff-be2a0d091497.png)

**Comment by AlbertRapp** [comment]
You're welcome. Happy to have helped you get there :)
